### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [arcade-songs/arcade-songs](https://hosted.weblate.org/projects/arcade-songs/arcade-songs/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by zetaraku** [comment]
@yangyangdaji Hi! Thanks for your contribution!
Just to be sure, do other `zh-Hans` translations look good to you as a native Simplified Chinese user?

**Comment by yangyangdaji** [comment]
yes

**Comment by zetaraku** [comment]
Thanks again! :)

**Comment by yangyangdaji** [comment]
Screenshot_20220917_151700
and some waiting to be synced😉

**Comment by zetaraku** [comment]
I should recheck this translation as "音乐" is usually translated to "music", not "song".

By the way, are you a regular arcade music game player?

**Comment by yangyangdaji** [comment]
> By the way, are you a regular arcade music game player?

Yes, I love Music game

> I should recheck this translation as "音乐" is usually translated to "music", not "song".
Modified

**Comment by zetaraku** [comment]
Since this PR is already closed, let's go to #5.

**Comment by yangyangdaji** [comment]
and some waiting to be synced😉




---Original---
From: "Raku ***@***.***&gt;
Date: Sat, Sep 17, 2022 15:14 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zetaraku/arcade-songs] Translations update from Hosted Weblate(PR #4)




 
Thanks again! :)

**Pull request merged**
